# Generated by Django 4.1.3 on 2023-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=90)),
                ("body", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("高等数学", "Math"),
                            ("我的软件", "Mysoftware"),
                            ("付费服务", "Paidservice"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("firstReleaseDate", models.DateTimeField(auto_now_add=True)),
                ("latestrevisionDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-latestrevisionDate"],
            },
        ),
    ]
