# Generated by Django 4.1.3 on 2023-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-latestrevisionDate"], "verbose_name": "Article"},
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("高等数学", "高等数学"), ("我的软件", "我的软件"), ("付费服务", "付费服务")],
                max_length=4,
            ),
        ),
    ]
