# Generated by Django 4.1.3 on 2023-11-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_options_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="isMarkdown",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
