# Generated by Django 4.1.3 on 2023-11-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_ismarkdown"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Post",
        ),
    ]
