# Generated by Django 4.1.3 on 2023-11-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-latestRevisionDate"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="仅支持HTML格式的内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="latestRevisionDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
