# Generated by Django 4.1.3 on 2023-11-11 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_post_firstreleasedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="firstReleaseDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="latestRevisionDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
