# Generated by Django 4.1.3 on 2023-11-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_post_firstreleasedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="firstReleaseDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="latestRevisionDate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
