# Generated by Django 4.1.3 on 2023-11-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_rename_category_post_categoryname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categoryName",
            new_name="category",
        ),
    ]
